// Auto-generated by LibreLane
module systolic_array(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk_i,
  input rst_n,
  input array_en,
  input[63:0] act_in,
  input[255:0] psum_in,
  output[255:0] psum_out,
  input[63:0] weight_shift_in,
  input[1:0] weight_shift_en,
  input swap_weights
);
endmodule
